# Generated by Django 4.2.28 on 2026-02-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='export_templates/', verbose_name='ملف القالب')),
                ('page_size', models.CharField(default='A4', max_length=20, verbose_name='حجم الصفحة')),
                ('orientation', models.CharField(default='portrait', max_length=20, verbose_name='الاتجاه')),
                ('margins', models.JSONField(blank=True, default=dict, verbose_name='الهوامش')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='organizations.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'قالب تصدير',
                'verbose_name_plural': 'قوالب التصدير',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('docx', 'Word'), ('pdf', 'PDF')], max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('file', models.FileField(blank=True, upload_to='exports/', verbose_name='الملف')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف')),
                ('progress', models.IntegerField(default=0, verbose_name='التقدم')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدء المعالجة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء المعالجة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='reports.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'مهمة تصدير',
                'verbose_name_plural': 'مهام التصدير',
                'ordering': ['-created_at'],
            },
        ),
    ]
