# Generated by Django 4.2.28 on 2026-02-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('section', 'Section Prompt'), ('summary', 'Summary Prompt'), ('chart', 'Chart Description')], max_length=20, verbose_name='النوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='المتغيرات')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='organizations.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'قالب Prompt',
                'verbose_name_plural': 'قوالب Prompt',
                'ordering': ['prompt_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50, verbose_name='نوع المصدر')),
                ('source_id', models.IntegerField(verbose_name='معرّف المصدر')),
                ('chunk_index', models.IntegerField(verbose_name='رقم الجزء')),
                ('text', models.TextField(verbose_name='النص')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='التضمين')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='البيانات الوصفية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='organizations.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'جزء مستند',
                'verbose_name_plural': 'أجزاء المستندات',
                'ordering': ['source_type', 'source_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='الـ Prompt')),
                ('context', models.TextField(blank=True, verbose_name='السياق')),
                ('response', models.TextField(verbose_name='الرد')),
                ('model', models.CharField(max_length=100, verbose_name='النموذج')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='الرموز المدخلة')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='الرموز المخرجة')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='إجمالي الرموز')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='التكلفة')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('success', models.BooleanField(default=True, verbose_name='ناجح')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='reports.reportsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'توليد AI',
                'verbose_name_plural': 'توليدات AI',
                'ordering': ['-generated_at'],
            },
        ),
    ]
