# Generated by Django 4.2.28 on 2026-02-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('source_type', models.CharField(choices=[('excel', 'ملف Excel'), ('api', 'API خارجي'), ('database', 'قاعدة بيانات'), ('manual', 'إدخال يدوي')], max_length=20, verbose_name='النوع')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'مصدر بيانات',
                'verbose_name_plural': 'مصادر البيانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_from', models.CharField(max_length=255, verbose_name='الجهة المطلوب منها')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='رمز الوصول')),
                ('template_file', models.FileField(upload_to='data_templates/', verbose_name='ملف القالب')),
                ('submitted_file', models.FileField(blank=True, upload_to='data_submissions/', verbose_name='الملف المرفوع')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الرد'), ('submitted', 'تم التقديم'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تذكير')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='عدد التذكيرات')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='reports.report', verbose_name='التقرير')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='reports.reportsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'طلب بيانات',
                'verbose_name_plural': 'طلبات البيانات',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('file', models.FileField(upload_to='data_files/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF'), ('other', 'أخرى')], default='excel', max_length=20, verbose_name='نوع الملف')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات المستخرجة')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='تم التحليل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='reports.report', verbose_name='التقرير')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='reports.reportsection', verbose_name='القسم')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف بيانات',
                'verbose_name_plural': 'ملفات البيانات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
