# Generated by Django 6.0.2 on 2026-03-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
        ('reports', '0003_dynamic_template_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='reports.report', verbose_name='التقرير'),
        ),
    ]
