# Generated by Django 6.0.2 on 2026-03-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_alter_datafile_report'),
        ('templates_app', '0002_dynamic_template_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='templates_app.entity', verbose_name='الجهة المسؤولة'),
        ),
    ]
