# Generated by Django 6.0.2 on 2026-03-02 21:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_add_entity_to_datafile'),
        ('organizations', '0001_initial'),
        ('reports', '0004_generatedreport_current_step_and_more'),
        ('templates_app', '0002_dynamic_template_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='السنة الأكاديمية'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف/ملاحظات'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='الإصدار الحالي'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='templates_app.item', verbose_name='البند/المؤشر'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية الفترة'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية الفترة'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='data_collection.datafile', verbose_name='الإصدار السابق'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجعة'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_files', to=settings.AUTH_USER_MODEL, verbose_name='راجعه'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('needs_revision', 'يحتاج تعديل')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='templates_app.entity', verbose_name='الجهة المسؤولة'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to='data_files/%Y/%m/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF'), ('word', 'Word'), ('image', 'صورة'), ('other', 'أخرى')], default='excel', max_length=20, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='reports.report', verbose_name='التقرير'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='reports.reportsection', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_data_files', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة'),
        ),
        migrations.CreateModel(
            name='DataCollectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفترة')),
                ('academic_year', models.CharField(max_length=20, verbose_name='السنة الأكاديمية')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('extended_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التمديد')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('open', 'مفتوحة'), ('extended', 'ممددة'), ('closed', 'مغلقة')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('reminder_days', models.JSONField(blank=True, default=list, verbose_name='أيام التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_periods', to='organizations.organization', verbose_name='المؤسسة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_periods', to='templates_app.template', verbose_name='القالب المستخدم')),
            ],
            options={
                'verbose_name': 'فترة جمع بيانات',
                'verbose_name_plural': 'فترات جمع البيانات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EntitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد العمل'), ('submitted', 'مُسلَّم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('needs_revision', 'يحتاج مراجعة')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='إجمالي البنود')),
                ('completed_items', models.PositiveIntegerField(default=0, verbose_name='البنود المكتملة')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الإنجاز')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='سُلِّم في')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='اعتُمد في')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entity_submissions', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='templates_app.entity', verbose_name='الجهة')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='data_collection.datacollectionperiod', verbose_name='فترة الجمع')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_submissions', to=settings.AUTH_USER_MODEL, verbose_name='سلّمه')),
            ],
            options={
                'verbose_name': 'تسليم جهة',
                'verbose_name_plural': 'تسليمات الجهات',
                'ordering': ['entity__name'],
                'unique_together': {('entity', 'period')},
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='data_collection.entitysubmission', verbose_name='التسليم'),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'تم الإنشاء'), ('uploaded', 'تم الرفع'), ('submitted', 'تم التسليم'), ('approved', 'تمت الموافقة'), ('rejected', 'تم الرفض'), ('revision_requested', 'طُلب تعديل'), ('revised', 'تم التعديل'), ('comment', 'تعليق')], max_length=20, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='data_collection.datafile', verbose_name='الملف')),
                ('entity_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='data_collection.entitysubmission', verbose_name='تسليم الجهة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
