# Generated by Django 6.0.2 on 2026-03-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_datafile_academic_year_datafile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionperiod',
            name='previous_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_periods', to='data_collection.datacollectionperiod', verbose_name='الفترة السابقة'),
        ),
    ]
