# Generated by Django 6.0.2 on 2026-03-18 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('templates_app', '0004_itemcomponent_ref_id_itemcomponent_references_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('period', models.CharField(max_length=50, verbose_name='الفترة')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='بداية الفترة')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('collecting', 'جمع البيانات'), ('reviewing', 'مراجعة'), ('generating', 'جاري التوليد'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('previous_year_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات السنة السابقة')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='المؤسسة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('components', models.JSONField(default=list, help_text='قائمة مكونات البند بالترتيب: فقرات، جداول، أشكال', verbose_name='المكونات')),
                ('source', models.CharField(choices=[('template', 'من القالب الافتراضي'), ('previous_report', 'من تقرير سابق'), ('manual', 'إدخال يدوي'), ('ai_suggested', 'اقتراح AI')], default='template', max_length=20, verbose_name='المصدر')),
                ('style_sample', models.TextField(blank=True, help_text='نص من التقرير السابق يُستخدم كمرجع أسلوب للـ AI', verbose_name='عينة الأسلوب')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='templates_app.item', verbose_name='البند')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_structures', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'هيكل بند',
                'verbose_name_plural': 'هياكل البنود',
                'ordering': ['item__axis__order', 'item__order'],
                'unique_together': {('project', 'item')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('docx', 'Word'), ('pdf', 'PDF'), ('html', 'HTML'), ('xlsx', 'Excel')], max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='التقدم')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='الخطوة الحالية')),
                ('file', models.FileField(blank=True, upload_to='generated_reports/', verbose_name='الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='خيارات التوليد')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'تقرير مولّد',
                'verbose_name_plural': 'التقارير المولّدة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المسؤول')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('invite_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='رمز الدعوة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('invited', 'تم الدعوة'), ('in_progress', 'جاري الإدخال'), ('submitted', 'تم الإرسال'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الدعوة')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تذكير')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='عدد التذكيرات')),
                ('first_access_at', models.DateTimeField(blank=True, null=True, verbose_name='أول وصول')),
                ('last_access_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر وصول')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='templates_app.entity', verbose_name='الجهة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مساهم',
                'verbose_name_plural': 'المساهمون',
                'ordering': ['entity__priority', 'entity__name'],
                'unique_together': {('project', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_id', models.CharField(help_text='مثل: p1, p2, p3', max_length=20, verbose_name='معرّف المكون')),
                ('content', models.TextField(blank=True, help_text='النص المولّد بالـ AI — قد يحتوي على {ref:t1} للمراجع', verbose_name='المحتوى المولّد')),
                ('manual_edit', models.TextField(blank=True, help_text='إذا عدّل المستخدم النص — يُستخدم بدل content', verbose_name='التعديل اليدوي')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('generating', 'جاري التوليد'), ('generated', 'تم التوليد'), ('edited', 'معدّل يدوياً'), ('approved', 'معتمد'), ('failed', 'فشل التوليد')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('previous_content', models.TextField(blank=True, verbose_name='المحتوى السابق')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='نموذج AI')),
                ('ai_tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens الإدخال')),
                ('ai_tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens الإخراج')),
                ('ai_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='التكلفة')),
                ('generation_time_ms', models.PositiveIntegerField(default=0, verbose_name='وقت التوليد (ms)')),
                ('prompt_used', models.TextField(blank=True, verbose_name='الـ Prompt المستخدم')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contents', to=settings.AUTH_USER_MODEL, verbose_name='ولّده')),
                ('item_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='reports.itemstructure', verbose_name='هيكل البند')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'محتوى مولّد',
                'verbose_name_plural': 'المحتويات المولّدة',
                'ordering': ['item_structure__item__axis__order', 'item_structure__item__order'],
                'unique_together': {('item_structure', 'component_id')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True, verbose_name='القيمة')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('admin_value', models.JSONField(blank=True, null=True, verbose_name='قيمة المدير')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المدير')),
                ('overridden_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.contributor', verbose_name='المساهم')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='templates_app.item', verbose_name='البند')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_responses', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'استجابة',
                'verbose_name_plural': 'الاستجابات',
                'ordering': ['item__axis__order', 'item__order'],
                'unique_together': {('project', 'contributor', 'item')},
            },
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(default=list, verbose_name='الصفوف')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='table_data/', verbose_name='الملف المصدر')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='reports.contributor', verbose_name='المساهم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='reports.project', verbose_name='المشروع')),
                ('table_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='templates_app.tabledefinition', verbose_name='تعريف الجدول')),
            ],
            options={
                'verbose_name': 'بيانات جدول',
                'verbose_name_plural': 'بيانات الجداول',
                'unique_together': {('project', 'contributor', 'table_definition')},
            },
        ),
    ]
