# Generated by Django 4.2.28 on 2026-02-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('collecting', 'جمع البيانات'), ('generating', 'جاري التوليد'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('exported', 'تم التصدير')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('exported_file', models.FileField(blank=True, upload_to='exports/', verbose_name='الملف المصدّر')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصدير')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization', verbose_name='المؤسسة')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('content_html', models.TextField(blank=True, verbose_name='المحتوى HTML')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='البيانات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار البيانات'), ('ready', 'جاهز للتوليد'), ('generating', 'جاري التوليد'), ('generated', 'تم التوليد'), ('edited', 'معدّل'), ('approved', 'معتمد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_sections', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='التقرير')),
                ('template_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sections', to='templates_app.templatesection', verbose_name='قسم القالب')),
            ],
            options={
                'verbose_name': 'قسم التقرير',
                'verbose_name_plural': 'أقسام التقرير',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='التعليق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report', verbose_name='التقرير')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.reportsection', verbose_name='القسم')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReportChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('chart_type', models.CharField(choices=[('bar', 'أعمدة'), ('pie', 'دائري'), ('line', 'خطي'), ('area', 'مساحة')], default='bar', max_length=20, verbose_name='نوع الرسم')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('image', models.ImageField(blank=True, upload_to='charts/', verbose_name='صورة الرسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='reports.reportsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'رسم بياني',
                'verbose_name_plural': 'الرسوم البيانية',
                'ordering': ['order'],
            },
        ),
    ]
