# Generated by Django 4.2.28 on 2026-03-01 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المسؤول')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('invite_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='رمز الدعوة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('invited', 'تم الدعوة'), ('in_progress', 'جاري الإدخال'), ('submitted', 'تم الإرسال'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الدعوة')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تذكير')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='عدد التذكيرات')),
                ('first_access_at', models.DateTimeField(blank=True, null=True, verbose_name='أول وصول')),
                ('last_access_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر وصول')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
            ],
            options={
                'verbose_name': 'مساهم',
                'verbose_name_plural': 'المساهمون',
                'ordering': ['entity__priority', 'entity__name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('docx', 'Word'), ('pdf', 'PDF'), ('html', 'HTML'), ('xlsx', 'Excel')], max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('file', models.FileField(upload_to='generated_reports/', verbose_name='الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='خيارات التوليد')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
            ],
            options={
                'verbose_name': 'تقرير مولّد',
                'verbose_name_plural': 'التقارير المولّدة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('period', models.CharField(max_length=50, verbose_name='الفترة')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='بداية الفترة')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('collecting', 'جمع البيانات'), ('reviewing', 'مراجعة'), ('generating', 'جاري التوليد'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('previous_year_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات السنة السابقة')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True, verbose_name='القيمة')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('admin_value', models.JSONField(blank=True, null=True, verbose_name='قيمة المدير')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المدير')),
                ('overridden_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'استجابة',
                'verbose_name_plural': 'الاستجابات',
                'ordering': ['item__axis__order', 'item__order'],
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقرير (قديم)', 'verbose_name_plural': 'التقارير (قديم)'},
        ),
        migrations.AlterModelOptions(
            name='reportsection',
            options={'ordering': ['order'], 'verbose_name': 'قسم التقرير (قديم)', 'verbose_name_plural': 'أقسام التقرير (قديم)'},
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(default=list, verbose_name='الصفوف')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='table_data/', verbose_name='الملف المصدر')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='reports.contributor', verbose_name='المساهم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'بيانات جدول',
                'verbose_name_plural': 'بيانات الجداول',
            },
        ),
    ]
