# Generated by Django 4.2.28 on 2026-03-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_dynamic_template_system'),
        ('reports', '0002_dynamic_template_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='table_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='templates_app.tabledefinition', verbose_name='تعريف الجدول'),
        ),
        migrations.AddField(
            model_name='response',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.contributor', verbose_name='المساهم'),
        ),
        migrations.AddField(
            model_name='response',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='templates_app.item', verbose_name='البند'),
        ),
        migrations.AddField(
            model_name='response',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_responses', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة'),
        ),
        migrations.AddField(
            model_name='response',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='templates_app.template', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='templates_app.entity', verbose_name='الجهة'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='reports.project', verbose_name='المشروع'),
        ),
        migrations.AlterUniqueTogether(
            name='tabledata',
            unique_together={('project', 'contributor', 'table_definition')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('project', 'contributor', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('project', 'entity')},
        ),
    ]
