# Generated by Django 6.0.2 on 2026-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dynamic_template_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='current_step',
            field=models.CharField(blank=True, max_length=100, verbose_name='الخطوة الحالية'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='التقدم'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, upload_to='generated_reports/', verbose_name='الملف'),
        ),
    ]
