# Generated by Django 6.0.2 on 2026-03-04 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_datafile_academic_year_datafile_description_and_more'),
        ('reports', '0004_generatedreport_current_step_and_more'),
        ('templates_app', '0002_dynamic_template_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('content_html', models.TextField(blank=True, verbose_name='المحتوى HTML')),
                ('tables_data', models.JSONField(blank=True, default=list, verbose_name='بيانات الجداول')),
                ('charts_data', models.JSONField(blank=True, default=list, verbose_name='بيانات الرسوم')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات المصدرية')),
                ('source_data_hash', models.CharField(blank=True, max_length=64, verbose_name='hash البيانات')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('generating', 'جاري التوليد'), ('generated', 'تم التوليد'), ('edited', 'معدّل'), ('approved', 'معتمد')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('previous_content', models.TextField(blank=True, verbose_name='المحتوى السابق')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='نموذج AI')),
                ('ai_tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens الإدخال')),
                ('ai_tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens الإخراج')),
                ('ai_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='التكلفة')),
                ('generation_time_ms', models.PositiveIntegerField(default=0, verbose_name='وقت التوليد (ms)')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drafts', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='templates_app.axis', verbose_name='المحور')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_drafts', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to=settings.AUTH_USER_MODEL, verbose_name='ولّده')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_drafts', to='data_collection.datacollectionperiod', verbose_name='فترة الجمع')),
            ],
            options={
                'verbose_name': 'مسودة محور',
                'verbose_name_plural': 'مسودات المحاور',
                'ordering': ['axis__order'],
                'unique_together': {('period', 'axis')},
            },
        ),
    ]
