# Generated by Django 6.0.2 on 2026-03-04 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_add_item_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('preview', models.ImageField(blank=True, upload_to='output_templates/', verbose_name='معاينة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'قالب مخرجات',
                'verbose_name_plural': 'قوالب المخرجات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='إعدادات الرسم'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='manual_content',
            field=models.JSONField(blank=True, default=list, verbose_name='محتوى يدوي'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='table_data',
            field=models.JSONField(blank=True, default=list, verbose_name='بيانات الجدول'),
        ),
        migrations.CreateModel(
            name='DraftAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='draft_attachments/', verbose_name='الملف')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='التعليق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('axis_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.axisdraft', verbose_name='مسودة المحور')),
                ('item_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.itemdraft', verbose_name='مسودة البند')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('generate', 'توليد'), ('edit', 'تعديل'), ('approve', 'اعتماد'), ('revert', 'تراجع'), ('reject', 'رفض'), ('add_attachment', 'إضافة مرفق'), ('remove_attachment', 'حذف مرفق')], max_length=20, verbose_name='الإجراء')),
                ('field_changed', models.CharField(blank=True, max_length=100, verbose_name='الحقل المتغير')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('axis_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.axisdraft', verbose_name='مسودة المحور')),
                ('item_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.itemdraft', verbose_name='مسودة البند')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تعديل',
                'verbose_name_plural': 'سجل التعديلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'نص'), ('table', 'جدول'), ('chart', 'رسم بياني'), ('image', 'صورة')], max_length=20, verbose_name='النوع')),
                ('source', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي'), ('mixed', 'مختلط')], default='auto', max_length=20, verbose_name='المصدر')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('width', models.CharField(default='full', max_length=20, verbose_name='العرض')),
                ('required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='reports.outputtemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'مكون مخرجات',
                'verbose_name_plural': 'مكونات المخرجات',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='output_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_drafts', to='reports.outputtemplate', verbose_name='قالب المخرجات'),
        ),
    ]
