# Generated by Django 6.0.2 on 2026-03-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_previous_period'),
        ('reports', '0007_output_templates_and_history'),
        ('templates_app', '0003_add_item_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='axisdraft',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemdraft',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='axisdraft',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='axis_drafts', to='reports.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_drafts', to='reports.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='axisdraft',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='axis_drafts', to='data_collection.datacollectionperiod', verbose_name='فترة الجمع'),
        ),
        migrations.AlterField(
            model_name='itemdraft',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_drafts', to='data_collection.datacollectionperiod', verbose_name='فترة الجمع'),
        ),
        migrations.AddConstraint(
            model_name='axisdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False)), fields=('period', 'axis'), name='unique_period_axis_draft'),
        ),
        migrations.AddConstraint(
            model_name='axisdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'axis'), name='unique_project_axis_draft'),
        ),
        migrations.AddConstraint(
            model_name='itemdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False)), fields=('period', 'item'), name='unique_period_item_draft'),
        ),
        migrations.AddConstraint(
            model_name='itemdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'item'), name='unique_project_item_draft'),
        ),
    ]
