# Generated by Django 6.0.2 on 2026-03-17 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_axisdraft_unique_together_and_more'),
        ('templates_app', '0004_itemcomponent_ref_id_itemcomponent_references_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_source', models.CharField(blank=True, help_text='مثل: توزيع_حسب_الكلية, توزيع_حسب_الرتبة', max_length=100, verbose_name='مصدر البيانات')),
                ('data_type', models.CharField(choices=[('table', 'جدول تفصيلي'), ('time_series', 'سلسلة زمنية'), ('breakdown', 'تفصيل/توزيع'), ('comparison', 'مقارنة'), ('raw_data', 'بيانات خام')], default='table', max_length=20, verbose_name='نوع البيانات')),
                ('data', models.JSONField(default=dict, help_text='البيانات التفصيلية بصيغة JSON', verbose_name='البيانات')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='detailed_responses/', verbose_name='الملف المصدر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_responses', to='reports.contributor', verbose_name='المساهم')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_responses', to='templates_app.item', verbose_name='البند')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_responses', to='reports.project', verbose_name='المشروع')),
                ('response', models.ForeignKey(blank=True, help_text='ربط بـ Response الأصلي (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_data', to='reports.response', verbose_name='الاستجابة')),
                ('table_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_responses', to='templates_app.tabledefinition', verbose_name='تعريف الجدول')),
            ],
            options={
                'verbose_name': 'بيانات تفصيلية',
                'verbose_name_plural': 'البيانات التفصيلية',
                'ordering': ['item__axis__order', 'item__order'],
            },
        ),
        migrations.CreateModel(
            name='ItemStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('components', models.JSONField(default=list, help_text='قائمة مكونات البند بالترتيب: فقرات، جداول، أشكال', verbose_name='المكونات')),
                ('source', models.CharField(choices=[('template', 'من القالب الافتراضي'), ('previous_report', 'من تقرير سابق'), ('manual', 'إدخال يدوي'), ('ai_suggested', 'اقتراح AI')], default='template', max_length=20, verbose_name='المصدر')),
                ('style_sample', models.TextField(blank=True, help_text='نص من التقرير السابق يُستخدم كمرجع أسلوب للـ AI', verbose_name='عينة الأسلوب')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='templates_app.item', verbose_name='البند')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_structures', to='reports.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'هيكل بند',
                'verbose_name_plural': 'هياكل البنود',
                'ordering': ['item__axis__order', 'item__order'],
                'unique_together': {('project', 'item')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_id', models.CharField(help_text='مثل: p1, p2, p3', max_length=20, verbose_name='معرّف المكون')),
                ('content', models.TextField(blank=True, help_text='النص المولّد بالـ AI — قد يحتوي على {ref:t1} للمراجع', verbose_name='المحتوى المولّد')),
                ('manual_edit', models.TextField(blank=True, help_text='إذا عدّل المستخدم النص — يُستخدم بدل content', verbose_name='التعديل اليدوي')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('generating', 'جاري التوليد'), ('generated', 'تم التوليد'), ('edited', 'معدّل يدوياً'), ('approved', 'معتمد'), ('failed', 'فشل التوليد')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('previous_content', models.TextField(blank=True, verbose_name='المحتوى السابق')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='نموذج AI')),
                ('ai_tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens الإدخال')),
                ('ai_tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens الإخراج')),
                ('ai_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='التكلفة')),
                ('generation_time_ms', models.PositiveIntegerField(default=0, verbose_name='وقت التوليد (ms)')),
                ('prompt_used', models.TextField(blank=True, verbose_name='الـ Prompt المستخدم')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contents', to=settings.AUTH_USER_MODEL, verbose_name='ولّده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='reports.project', verbose_name='المشروع')),
                ('item_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='reports.itemstructure', verbose_name='هيكل البند')),
            ],
            options={
                'verbose_name': 'محتوى مولّد',
                'verbose_name_plural': 'المحتويات المولّدة',
                'ordering': ['item_structure__item__axis__order', 'item_structure__item__order'],
                'unique_together': {('item_structure', 'component_id')},
            },
        ),
    ]
