# Generated by Django 4.2.28 on 2026-02-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('structure', models.JSONField(blank=True, default=dict, verbose_name='الهيكل')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات التنسيق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'القوالب',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان بالإنجليزية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('section_type', models.CharField(choices=[('text', 'نص'), ('table', 'جدول'), ('chart', 'رسم بياني'), ('images', 'صور'), ('mixed', 'مختلط')], default='mixed', max_length=20, verbose_name='نوع القسم')),
                ('data_source', models.JSONField(blank=True, null=True, verbose_name='مصدر البيانات')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='Prompt للذكاء الاصطناعي')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات القسم')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'قسم القالب',
                'verbose_name_plural': 'أقسام القالب',
                'ordering': ['order'],
            },
        ),
    ]
