# Generated by Django 4.2.28 on 2026-03-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='Prompt للمقدمة')),
            ],
            options={
                'verbose_name': 'محور',
                'verbose_name_plural': 'المحاور',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-is_default', '-is_public', 'name'], 'verbose_name': 'قالب', 'verbose_name_plural': 'القوالب'},
        ),
        migrations.AlterModelOptions(
            name='templatesection',
            options={'ordering': ['order'], 'verbose_name': 'قسم القالب (قديم)', 'verbose_name_plural': 'أقسام القالب (قديم)'},
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('higher_education', 'التعليم العالي'), ('government', 'الحكومة'), ('corporate', 'الشركات'), ('healthcare', 'الصحة'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='template',
            name='export_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='إعدادات التصدير'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='قالب عام'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='الإصدار'),
        ),
        migrations.AlterField(
            model_name='template',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization', verbose_name='المؤسسة'),
        ),
        migrations.AlterField(
            model_name='template',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='الإعدادات'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('field_type', models.CharField(choices=[('text', 'نص قصير'), ('number', 'رقم'), ('percentage', 'نسبة مئوية'), ('currency', 'مبلغ مالي'), ('date', 'تاريخ'), ('rich_text', 'نص طويل منسق'), ('select', 'اختيار من قائمة'), ('multi_select', 'اختيار متعدد'), ('file', 'ملف'), ('image', 'صورة'), ('excel_import', 'استيراد من Excel'), ('table_static', 'جدول ثابت الصفوف'), ('table_dynamic', 'جدول متغير الصفوف'), ('table_hierarchical', 'جدول هرمي'), ('computed', 'محسوب تلقائياً'), ('year_comparison', 'مقارنة سنوية')], default='text', max_length=30, verbose_name='نوع الحقل')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='إعدادات الحقل')),
                ('formula', models.TextField(blank=True, verbose_name='المعادلة')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='الاعتماديات')),
                ('aggregation', models.CharField(choices=[('none', 'لا يوجد'), ('sum', 'مجموع'), ('average', 'متوسط'), ('count', 'عدد'), ('list', 'قائمة'), ('latest', 'آخر قيمة'), ('min', 'أقل قيمة'), ('max', 'أعلى قيمة'), ('concat', 'دمج نصي')], default='none', max_length=20, verbose_name='طريقة التجميع')),
                ('required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='Prompt للتحليل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='templates_app.axis', verbose_name='المحور')),
            ],
            options={
                'verbose_name': 'بند',
                'verbose_name_plural': 'البنود',
                'ordering': ['order'],
                'unique_together': {('axis', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('contact_role', models.CharField(blank=True, max_length=255, verbose_name='المسمى الوظيفي')),
                ('priority', models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('is_college', models.BooleanField(default=False, verbose_name='كلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('items', models.ManyToManyField(blank=True, related_name='entities', to='templates_app.item', verbose_name='البنود المسؤول عنها')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'جهة',
                'verbose_name_plural': 'الجهات',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChartDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('chart_type', models.CharField(choices=[('bar', 'أعمدة'), ('pie', 'دائري'), ('line', 'خطي'), ('area', 'مساحة'), ('stacked_bar', 'أعمدة متراكمة'), ('donut', 'حلقي')], default='bar', max_length=20, verbose_name='نوع الرسم')),
                ('data_source', models.JSONField(default=dict, verbose_name='مصدر البيانات')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='templates_app.axis', verbose_name='المحور')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_definitions', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'تعريف رسم بياني',
                'verbose_name_plural': 'تعريفات الرسوم البيانية',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='axis',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='templates_app.template', verbose_name='القالب'),
        ),
        migrations.CreateModel(
            name='TableDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('table_type', models.CharField(choices=[('static', 'ثابت الصفوف'), ('dynamic', 'متغير الصفوف'), ('hierarchical', 'هرمي'), ('excel_import', 'استيراد من Excel')], default='dynamic', max_length=20, verbose_name='نوع الجدول')),
                ('columns', models.JSONField(default=list, verbose_name='الأعمدة')),
                ('fixed_rows', models.JSONField(blank=True, default=list, verbose_name='الصفوف الثابتة')),
                ('levels', models.JSONField(blank=True, default=list, verbose_name='المستويات')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='table_templates/', verbose_name='ملف القالب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='templates_app.axis', verbose_name='المحور')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='templates_app.entity', verbose_name='الجهة المسؤولة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_definitions', to='templates_app.template', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'تعريف جدول',
                'verbose_name_plural': 'تعريفات الجداول',
                'ordering': ['order'],
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='axis',
            unique_together={('template', 'code')},
        ),
    ]
