# Generated by Django 6.0.2 on 2026-03-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_dynamic_template_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('text', 'نص'), ('text_ai', 'نص (توليد AI)'), ('table', 'جدول'), ('chart', 'رسم بياني'), ('image', 'صورة'), ('divider', 'فاصل')], max_length=20, verbose_name='نوع المكوّن')),
                ('source', models.CharField(choices=[('auto', 'تلقائي من البيانات'), ('ai', 'توليد AI'), ('manual', 'إدخال يدوي'), ('reference', 'مرجع لتعريف موجود')], default='auto', max_length=20, verbose_name='المصدر')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('chart_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_components', to='templates_app.chartdefinition', verbose_name='مرجع الرسم')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='templates_app.item', verbose_name='البند')),
                ('table_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_components', to='templates_app.tabledefinition', verbose_name='مرجع الجدول')),
            ],
            options={
                'verbose_name': 'مكوّن بند',
                'verbose_name_plural': 'مكوّنات البنود',
                'ordering': ['order'],
                'unique_together': {('item', 'order')},
            },
        ),
    ]
