# Generated by Django 6.0.2 on 2026-03-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_add_item_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomponent',
            name='ref_id',
            field=models.CharField(blank=True, help_text='مثل: p1, t1, c1 — يُستخدم في نظام المراجع {ref:t1}', max_length=20, verbose_name='معرّف المرجع'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='قائمة ref_ids المكونات المرتبطة، مثل: ["t1", "c1"]', verbose_name='المراجع'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='component_type',
            field=models.CharField(choices=[('text', 'نص'), ('text_ai', 'نص (توليد AI)'), ('heading', 'عنوان فرعي'), ('table', 'جدول'), ('chart', 'رسم بياني'), ('image', 'صورة'), ('divider', 'فاصل')], max_length=20, verbose_name='نوع المكوّن'),
        ),
    ]
